name: Andrology Statistics Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install poethepoet==0.20.0
        poetry install
    - name: Lint with black
      run: |
        poetry poe lint
    - name: Type check with mypy
      run: |
        poetry poe type-check
    - name: Test with pytest
      run: |
        poetry poe test
